/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public")
    }

    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.aikar.co/content/groups/aikar/")
    }

    maven {
        url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    }

    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.tcoded.com/releases/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("com.comphenix.protocol:ProtocolLib:5.3.0")
    api("co.aikar:acf-bukkit:0.5.1-SNAPSHOT")
    api("net.kyori:adventure-text-serializer-bungeecord:4.4.1-SNAPSHOT")
    api("net.kyori:adventure-text-serializer-gson:4.23.0")
    api("net.kyori:adventure-text-serializer-gson-legacy-impl:4.23.0")
    api("net.kyori:adventure-text-serializer-json:4.23.0")
    api("net.kyori:adventure-text-serializer-json-legacy-impl:4.23.0")
    api("net.kyori:adventure-api:4.23.0")
    api("net.kyori:adventure-nbt:4.23.0")
    api("net.kyori:adventure-key:4.23.0")
    api("net.kyori:adventure-platform-api:4.4.1-SNAPSHOT")
    api("net.kyori:adventure-platform-bukkit:4.4.1-SNAPSHOT")
    api("net.kyori:adventure-platform-facet:4.4.1-SNAPSHOT")
    api("net.kyori:adventure-platform-viaversion:4.4.1-SNAPSHOT")
    api("net.kyori:option:1.1.0")
    api("org.apache.maven.scm:maven-scm-provider-gitexe:2.1.0")
    api("org.bstats:bstats-bukkit:3.0.2")
    api("com.sk89q.worldguard:worldguard-core:7.0.7")
    api("com.sk89q.worldguard:worldguard-legacy:7.0.0-SNAPSHOT")
    api("org.apache.tomcat:tomcat-jdbc:10.1.24")
    api("org.jetbrains:annotations:24.1.0")
    api("com.google.guava:guava:33.2.0-jre")
    api("com.tcoded:FoliaLib:0.5.1")
    testImplementation("org.assertj:assertj-core:3.25.3")
    testImplementation("com.h2database:h2:2.2.224")
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.0-M2")
    testImplementation("org.mockito:mockito-core:5.12.0")
    testImplementation("org.mockito:mockito-inline:5.2.0")
    compileOnly("me.clip:placeholderapi:2.11.6")
    compileOnly("org.spigotmc:spigot-api:1.21.7-R0.1-SNAPSHOT")
    compileOnly("com.sk89q.worldedit:worldedit-bukkit:7.2.0-SNAPSHOT")
}

group = "com.gmail.nossr50.mcMMO"
version = "2.2.041-SNAPSHOT"
description = "mcMMO"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
